### ISSUE TITLE
Turn of rainbow lights when custom colors are detected

### ISSUE THREAD

**Issue by Phoenix616** [CycleWeeb/JustRainbowLights#2]
Some songs have custom colors (e.g. [Ghosts n Stuff](https://bsaber.com/songs/2da4/)) and the rainbow lights look a bit weird with these custom colored blocks/sabers. Would it be possible to detect such songs and not show rainbow lights there? (Maybe via a settings toggle?)

**Comment by cycle00** [comment]
there is a toggle in mod settings to turn it off manually, but who knows, I might make a toggle to detect songs like these and turn off the rainbow lights but I might not
